"""Optional advisory bridges kept separate from deterministic ARX evidence."""

from .audit import (
    AuditError,
    MemoryTransmissionAudit,
    TransmissionAudit,
    TransmissionEvent,
    TransportState,
    default_transmission_audit,
)
from .context import (
    ANALYSIS_MODES,
    AdvisoryChatMode,
    AdvisoryContext,
    ContextSelection,
    build_advisory_context,
    build_advisory_prompt,
    build_general_chat_context,
    build_intelligence_context,
    redact_external,
)
from .credentials import (
    CredentialError,
    CredentialSource,
    CredentialState,
    CredentialStatus,
    CredentialUnreadable,
    ProviderCredentialResolver,
    WindowsDPAPICredentialStore,
    default_openai_credential_resolver,
    default_openai_credential_store,
    import_openai_credential_file,
)
from .health import ProviderHealth, ProviderHealthStatus, validate_provider_health
from .intelligence import (
    AdvisoryComparison,
    AskBothResult,
    ConversationRegistry,
    ProviderOutcome,
    ask_both,
    compare_advisories,
)
from .providers import (
    AdvisoryCancelled,
    AdvisoryResponse,
    AdvisoryTimeout,
    CodexCLIProvider,
    OpenAIProvider,
    ProviderAvailability,
    ProviderError,
)

__all__ = [
    "ANALYSIS_MODES",
    "AdvisoryCancelled",
    "AdvisoryChatMode",
    "AdvisoryComparison",
    "AdvisoryContext",
    "AdvisoryResponse",
    "AdvisoryTimeout",
    "AskBothResult",
    "AuditError",
    "CodexCLIProvider",
    "ContextSelection",
    "ConversationRegistry",
    "CredentialError",
    "CredentialSource",
    "CredentialState",
    "CredentialStatus",
    "CredentialUnreadable",
    "MemoryTransmissionAudit",
    "OpenAIProvider",
    "ProviderAvailability",
    "ProviderCredentialResolver",
    "ProviderError",
    "ProviderHealth",
    "ProviderHealthStatus",
    "ProviderOutcome",
    "TransmissionAudit",
    "TransmissionEvent",
    "TransportState",
    "WindowsDPAPICredentialStore",
    "ask_both",
    "build_advisory_context",
    "build_advisory_prompt",
    "build_general_chat_context",
    "build_intelligence_context",
    "compare_advisories",
    "default_openai_credential_resolver",
    "default_openai_credential_store",
    "default_transmission_audit",
    "import_openai_credential_file",
    "redact_external",
    "validate_provider_health",
]
