"""Project-aware semantic compatibility models and static Project DNA inspection."""

from .models import (
    Conflict,
    ExecutionContext,
    ExecutionResolution,
    ExplanationEdge,
    ExplanationGraph,
    ExplanationNode,
    Finding,
    ManifestRecord,
    Policy,
    ProjectDNA,
    ProjectPreflight,
    Provider,
    ProviderEdge,
    ProviderGraph,
    ProviderKind,
    Relevance,
    Requirement,
    RequirementEdge,
    RequirementEvaluation,
    ResolutionPlan,
    ResolutionStep,
    Satisfaction,
    Severity,
    SeverityDecision,
)
from .resolver import (
    infer_provider_kind,
    make_provider,
    provider_graph_from_machine,
    providers_from_machine,
    resolve_python,
)
from .engine import (
    evaluate_requirement,
    plan_resolution,
    preflight,
    project_preflight,
    severity_for,
)
from .scanner import MAX_MANIFEST_BYTES, inspect_project
from .versions import parse_python_version, python_version_satisfies

__all__ = [
    "Conflict",
    "ExecutionContext",
    "ExecutionResolution",
    "ExplanationEdge",
    "ExplanationGraph",
    "ExplanationNode",
    "Finding",
    "MAX_MANIFEST_BYTES",
    "ManifestRecord",
    "Policy",
    "ProjectDNA",
    "ProjectPreflight",
    "Provider",
    "ProviderEdge",
    "ProviderGraph",
    "ProviderKind",
    "Relevance",
    "Requirement",
    "RequirementEdge",
    "RequirementEvaluation",
    "ResolutionPlan",
    "ResolutionStep",
    "Satisfaction",
    "Severity",
    "SeverityDecision",
    "evaluate_requirement",
    "inspect_project",
    "infer_provider_kind",
    "make_provider",
    "parse_python_version",
    "provider_graph_from_machine",
    "providers_from_machine",
    "python_version_satisfies",
    "plan_resolution",
    "preflight",
    "project_preflight",
    "resolve_python",
    "severity_for",
]
