"""Project-aware semantic compatibility models and static Project DNA inspection."""

from .models import (
    Conflict,
    ExecutionContext,
    ExecutionResolution,
    ExplanationEdge,
    ExplanationGraph,
    ExplanationNode,
    Finding,
    ManifestRecord,
    Policy,
    ProjectDNA,
    ProjectPreflight,
    Provider,
    ProviderKind,
    Relevance,
    Requirement,
    RequirementEdge,
    RequirementEvaluation,
    ResolutionPlan,
    ResolutionStep,
    Satisfaction,
    Severity,
    SeverityDecision,
)
from .scanner import MAX_MANIFEST_BYTES, inspect_project

__all__ = [
    "Conflict",
    "ExecutionContext",
    "ExecutionResolution",
    "ExplanationEdge",
    "ExplanationGraph",
    "ExplanationNode",
    "Finding",
    "MAX_MANIFEST_BYTES",
    "ManifestRecord",
    "Policy",
    "ProjectDNA",
    "ProjectPreflight",
    "Provider",
    "ProviderKind",
    "Relevance",
    "Requirement",
    "RequirementEdge",
    "RequirementEvaluation",
    "ResolutionPlan",
    "ResolutionStep",
    "Satisfaction",
    "Severity",
    "SeverityDecision",
    "inspect_project",
]
